# main.py — HoodaRoutes Garmin push service.
# Creates a Course in your Garmin Connect account from a route, so the FR970
# can navigate it natively. Auth uses python-garminconnect (maintained; handles
# Garmin's mobile SSO + MFA + token refresh).
#
# Run init_auth.py ONCE locally to create the token store (handles MFA), then
# deploy the token files with the service. The server resumes without MFA.

import os
import io
import base64
import tarfile
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from garminconnect import Garmin

app = FastAPI(title="HoodaRoutes Garmin Push")
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"]
)

TOKENSTORE = os.environ.get("GARMINTOKENS", os.path.expanduser("~/.garminconnect"))
_client: Optional[Garmin] = None


def _restore_tokens() -> None:
    """Env-only deploy (Railway): if GARMIN_TOKENS_B64 is set (printed by
    init_auth.py), unpack the token store from it. No volume needed."""
    blob = os.environ.get("GARMIN_TOKENS_B64")
    if not blob or os.path.exists(os.path.join(TOKENSTORE, "oauth2_token.json")):
        return
    os.makedirs(TOKENSTORE, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(base64.b64decode(blob)), mode="r:gz") as tar:
        tar.extractall(TOKENSTORE)


def client() -> Garmin:
    """Lazily auth and cache the Garmin client. Resumes from the token store."""
    global _client
    if _client is not None:
        return _client
    _restore_tokens()
    g = Garmin(
        email=os.environ.get("GARMIN_EMAIL"),
        password=os.environ.get("GARMIN_PASSWORD"),
    )
    # Resume from saved tokens (created by init_auth.py). Falls back to a fresh
    # credential login only if the refresh token is gone — that path may need MFA.
    g.login(TOKENSTORE)
    _client = g
    return g


class GeoPoint(BaseModel):
    lat: float
    lng: float
    ele: Optional[float] = 0.0


class CourseReq(BaseModel):
    name: str
    activityType: str = "RUNNING"  # Garmin enum, e.g. RUNNING, TRAIL_RUNNING
    distanceM: float
    ascentM: float = 0.0
    descentM: float = 0.0
    geoPoints: List[GeoPoint]


@app.get("/health")
def health():
    return {"ok": True}


@app.post("/push-course")
def push_course(req: CourseReq):
    g = client()

    # Course schema follows Garmin's published Courses-API fields.
    payload = {
        "courseName": req.name,
        "description": "Generated by HoodaRoutes",
        "distance": req.distanceM,
        "elevationGain": req.ascentM,
        "elevationLoss": req.descentM,
        "coordinateSystem": "WGS84",
        "activityType": req.activityType,
        "geoPoints": [
            {"latitude": p.lat, "longitude": p.lng, "elevation": p.ele or 0.0}
            for p in req.geoPoints
        ],
    }

    try:
        # Authenticated POST through garth (python-garminconnect's session).
        #
        # ⚠️ VERIFY ONCE: connect.garmin.com's web course-service is not officially
        # documented. The payload above matches Garmin's published Courses-API
        # schema and works for most accounts. If Garmin returns 400/412, open
        # Garmin Connect in Chrome, create a course, capture the POST in DevTools,
        # and align the field names here. (See README for the official partner
        # Courses API, which uses exactly this schema.)
        resp = g.garth.post(
            "connectapi", "/course-service/course", json=payload, api=True
        )
        data = resp.json() if hasattr(resp, "json") else resp
        course_id = data.get("courseId") if isinstance(data, dict) else None
        return {"ok": True, "courseId": course_id}
    except Exception as e:
        # Reliable fallback so the route at least lands in the account:
        # write a GPX and upload it (appears under Activities; not a navigable
        # course, but proves auth + connectivity). Enable if you want it.
        raise HTTPException(status_code=502, detail=f"Garmin course push failed: {e}")
